### ISSUE TITLE
Missing Flush Method on Logzio Handler to purge Sender Queue

### ISSUE THREAD

**Issue by mkowalsky** [logzio/logzio-python-handler#12]
I am writing AWS Lambda functions in Python and I need to force the Queue in sender.py to empty out if it contains any buffered log messsages. The current implementation of the handler.py and sender.py  does not make this possible. 

My current work around is to extend the  `LogzioHandler` class to implement a `flush()` method so that `logging.shutdown()` or 'handler.flush()` will do something. I need to call one of these methods prior to the conclusion of my AWS lambda function, or else the logs messages never make it to Logzio.

**Comment by roiravhon** [comment]
Make sense.
It is possible to add a blocking function to sender.py that will drain the queue, and will return once it does, and hook it up to the shutdown event of the handler.

Want to PR this?

**Comment by mkowalsky** [comment]
I will need to experiment more with my current implementation,  Since in addition to extending `LogzioHandler` with my own Hanlder, i modified  parts of `LogzioSender` to force the internal Queue to drain and stop the while loop.  I will need to back out some of my changes and then reimplement them in a minimal fashion to make sure that I don't break the current behavior, ie supporting serverless and non-serverless use cases. 

I'll try to get a PR later on this week.

**Comment by roiravhon** [comment]
Thanks @mkowalsky!
Feel free to reach out to any help or questions you might have in the process :)

**Comment by roiravhon** [comment]
Hey @mkowalsky, just letting you know this was merged in https://github.com/logzio/logzio-python-handler/pull/18
