### ISSUE TITLE
No logging taking place with extra parameter

### ISSUE THREAD

**Issue by hardcodet** [logzio/logzio-python-handler#21]
Hi there

We're currently evaluation logz.io, and I tried getting the sample to run. Taking the code from the tests, I could see my log message in live tail, but only if there is no `extra` parameter. The following snippet does not work, but starts working as soon as I remove the `extra` field.

Is this a bug, or something I'm missing here with regards to configuration?

    def execute():
        logging_configuration = {
            "version": 1,
            "formatters": {
                "logzio": {
                    "format": '{"hello": "world"}'
                }
            },
            "handlers": {
                "LogzioHandler": {
                    "class": "logzio.handler.LogzioHandler",
                    "formatter": "logzio",
                    "level": "ERROR",
                    "token": "sFrTxyTpBZqKfXBNZCXmTKIWxwpLqaJo",
                    'logzio_type': "querybot",
                    'debug': False
                }
            },
            "loggers": {
                "test": {
                    "handlers": ["LogzioHandler"],
                    "level": "ERROR"
                }
            }
        }

        try:
            logging.config.dictConfig(logging_configuration)
            logger = logging.getLogger('test')
            result = logger.error("resolving pending locations", extra={"hello": "world"})
        except Exception as ex:
            print("logging exception: " + str(ex))

**Comment by hardcodet** [comment]
Ok, seems there is something wrong with live tail - I'm seeing the messages now in Kibana. Weirdly enough, only about half are reported in live tail (they are all exactly the same).

**Comment by roiravhon** [comment]
@hardcodet Live tail is only working on the "message" field when filtering. Might be related?

**Comment by hardcodet** [comment]
Dunno - it's no big deal for now though. Thanks for the quick turnaround!

**Comment by roiravhon** [comment]
Did you reach out to support? We can create an internal ticket if there is an issue there
