### ISSUE TITLE
Extra logged multiple times (may cause error on portal)

### ISSUE THREAD

**Issue by hardcodet** [logzio/logzio-python-handler#22]
Maybe I chasing a red herring here, but I ended up with error on Kibana (see at the end of the post), and I noticed that one of my extras appears in two fields in the outputted JSON. Here's my code to log a `foostamp`

     ts = (now + datetime.timedelta(minutes=-1 * num % 500)).isoformat() + "Z"
     logger.error("Load Test", extra={"nbr": num % 5, "foostamp": ts})

Now, in Kibana, I'm seeing this JSON being logged: Notice the two `foostamp` keys, while the `nbr` only appears once:

    {
      "_index": "logzioCustomerIndexxxx_v2",
      "_type": "querybot",
      "_id": "someidhere",
      "_version": 1,
      "_score": null,
      "_source": {
        "app": "querybot",
        "logger": "test",
        "log_level": "ERROR",
        "type": "querybot",
        "message": "Load Test",
        "tags": [
          "_logz_http_bulk_json_8070"
        ],
        "@timestamp": "2018-04-29T11:33:42.941Z",
        "line_number": 65,
        "foostamp": "2018-04-29T11:39:41.652168Z",
        "path_name": "D:\\xxx\\commands\\commands.py",
        "nbr": 4
      },
      "fields": {
        "@timestamp": [
          1525001622941
        ],
        "foostamp": [
          "2018-04-29T11:39:41.652168Z"
        ]
      },
      "sort": [
        1525001622941
      ]
    }

Furthermore, I changed the field mapping for the `foostamp` property in the portal in order to have it indexed as a timestamp, not a string. However, when I then try to visualize it, I end up with the following Kibana error:

`Request to Elasticsearch failed: {"error":{"root_cause":[],"type":"search_phase_execution_exception","reason":"","phase":"fetch","grouped":true,"failed_shards":[],"caused_by":{"type":"aggregation_execution_exception","reason":"Merging/Reducing the aggregations failed when computing the aggregation [3] because the field you gave in the aggregation query existed as two different types in two different indices"}},"status":503}`

Is that error potentially related to the duplicate fields, of which one is now mapped to a string, and the other would be a timestamp?

**Comment by roiravhon** [comment]
Since I think this is not related to the python handler, can you please reach out to support via the in-app chat icon?
They should be able to diagnose the issue from the context of your account

**Comment by roiravhon** [comment]
You can utilize Subaccounts for that, or distinguish them with "type".

**Comment by hardcodet** [comment]
awesome, thanks. btw, support is unavailable because the chat functionality seems to be broken, at least on Firefox - maybe you can escalate that internally. at least, now that you mentioned it, I know what that empty circle on the UI is :)

![image](https://user-images.githubusercontent.com/873009/39407031-28140172-4bc0-11e8-9ca5-118e70098e89.png)

**Comment by roiravhon** [comment]
Wierd, that is usually working on firefox.
Please email support@logz.io with that, and they will reach out and work with you to solve all problems :)
