### ISSUE TITLE
KeyError: 'formatters'

### ISSUE THREAD

**Issue by nathan30** [logzio/logzio-python-handler#29]
Hi,
I'm trying to use this python handler into my python script and I have the following error : `KeyError: 'formatters'`
Here is my conf : 

```
[handlers]
keys=LogzioHandler

[handler_LogzioHandler]
class=logzio.handler.LogzioHandler
formatter=logzioFormat
args=('token', 'python',3, 'https://listener.logz.io:8071', 'True')

[formatters]
keys=logzioFormat

[loggers]
keys=root

[logger_root]
handlers=LogzioHandler
level=INFO

[formatter_logzioFormat]
format={"additional_field": "value"}
```
Any idea of the problem ? :/

**Comment by roiravhon** [comment]
Hey @nathan30!
This looks right.

Where are you getting the error from?
How do you initialize the logger?

**Comment by nathan30** [comment]
Hey @roiravhon, thanks for your quick answer ! :)
I thought because I'm using python 3.5 I had to use `pip3` to install the handler. But after some test and install it with `pip` and now it's working perfectly :)
Thanks a lot for your work !

**Comment by roiravhon** [comment]
Amazing :)
Good luck!
