### ISSUE TITLE
Message published on AWS lambda might not be delivered

### ISSUE THREAD

**Issue by simonvanderveldt** [logzio/logzio-python-handler#30]
Hi!

I have a small question/issue, which seems related to https://github.com/logzio/logzio-python-handler/issues/12 and https://github.com/logzio/logzio-python-handler/pull/18

When using this library/handler within a lambda the metrics/logs we're sending don't end up in logzio. This happens because the handler apparently does the actual sending of the logs asynchronously combined with the fact that for some reason the AWS Lambda environment doesn't trigger the `flush()` function of the logger, which it normally does through `logging.shutdown()` https://github.com/python/cpython/blob/3.7/Lib/logging/__init__.py#L1988 which is registered as an atexit exit handler.

For now we're calling `metrics_logger.handlers[0].flush()` at the end of our lambda code, which works, but is kinda ugly.

I was wondering if there are better ways to do this? Or if it would boil down to kindly asking Amazon to make the lambda environment adhere to the regular Python conventions.

Alternatively maybe the handler can be created with a `synchronous` flag or something like that which ensures messages always gets published immediately?

**Comment by idohalevi** [comment]
@simonvanderveldt 
Hi, I will take a look ASAP.

**Comment by simonvanderveldt** [comment]
@idohalevi Have you been able to make some progress on this?

**Comment by idohalevi** [comment]
@simonvanderveldt 
Hi, because of the holidays here I didn't have time yet to check it out.

**Comment by simonvanderveldt** [comment]
@idohalevi OK, no problem. Thanks for the confirmation!
