### ISSUE TITLE
Add support for pypy2 and pypy3

### ISSUE THREAD

**Issue by rudaporto** [logzio/logzio-python-handler#32]
When using this library in `pypy3` the logging is not being sent to LogzIO and there is no warning.

**Comment by roiravhon** [comment]
Can you please provide your configuration?
This library is tested against python 3.3 and up

**Comment by rudaporto** [comment]
I'm using the handler class directly:

`
handler = LogzioHandler(
        LOGZIO_TOKEN,
        LOGZIO_TYPE,
        LOGZIO_DRAIN,
        LOGZIO_ENDPOINT
)
logger.addHandler(handler)
`
The issue happens when running with PyPy3 (3.5 - 6.0.0) portable binary:
https://bitbucket.org/squeaky/portable-pypy/downloads/pypy3.5-6.0.0-linux_x86_64-portable.tar.bz2

Should we add `pypy2` and `pypy3` in the build to check if there are issues?

**Comment by rudaporto** [comment]
> This setup is working on the non-portable version?

Sorry, what do you mean about "non-portable version"?

This is the link for Travis builds:
- https://travis-ci.org/rudaporto/logzio-python-handler

**Comment by rudaporto** [comment]
There is only one compatibility issue that is the use of `sys.getsizeof` that is not supported in the PyPy interpreter and it's documented here:

- http://doc.pypy.org/en/latest/cpython_differences.html#miscellaneous

> sys.getsizeof() always raises TypeError. This is because a memory profiler using this function is most likely to give results inconsistent with reality on PyPy. It would be possible to have sys.getsizeof() return a number (with enough work), but that may or may not represent how much memory the object uses. It doesn’t even make really sense to ask how much one object uses, in isolation with the rest of the system. For example, instances have maps, which are often shared across many instances; in this case the maps would probably be ignored by an implementation of sys.getsizeof(), but their overhead is important in some cases if they are many instances with unique maps. Conversely, equal strings may share their internal string data even if they are different objects—or empty containers may share parts of their internals as long as they are empty. Even stranger, some lists create objects as you read them; if you try to estimate the size in memory of range(10**6) as the sum of all items’ size, that operation will by itself create one million integer objects that never existed in the first place. Note that some of these concerns also exist on CPython, just less so. For this reason we explicitly don’t implement sys.getsizeof().

**Comment by rudaporto** [comment]
The question here is how proper check the size of the UTF-8 encoded strings in Python 2 and 3 to avoid reaching the payload size limit.

We could move to use `len(payload) * 4` for all cases since the data was encoded by `json.dumps` as UTF-8 strings.

```python
>>> log = 'My name is Rudá'
>>> import json
>>> payload = json.dumps(log)
>>> import sys
>>> sys.getsizeof(payload)
71
>>> len(payload)
22 # 88 will be the result in this implementation for pypy 2 and 3
```

**Comment by roiravhon** [comment]
Not sure that is a valid option...
There is no other way to get the size of a data structure?

**Comment by rudaporto** [comment]
@roiravhon why are you not sure that this is a valid option?

The goal of this check is to avoid reaching payload size the limit.
I guess this is enough and simple since we are dealing with Unicode strings.

**Comment by rudaporto** [comment]
@roiravhon tell me more about that, examples?

I think you are overthinking about something that's simple.
We are talking about UTF-8 encoded strings (since it was encoded when passed to the queue).

If you have a better working idea we can discuss but the point is that this library does not support now `pypy`. It can support it with this patch and all tests pass.

The good enough is the enemy of perfect. And if you research about it you gonna find that's there is not a perfect solution for this. If you have it, please release to the world since it will be a better place.

I'm using the fork and can use it for my own, but I can not see we are moving somewhere with this conversation. 

I guess the this is an open source project for a reason and so if you want collaboration please bring something to the table that will move things on.

And by the way, `len(str)` is counting the number of chars in an immutable Unicode string and that's why I've multiple by four.

**Comment by roiravhon** [comment]
"that's why I've multiple by four." is exactly the potential issue.
But I might be over thinking it.

@idohalevi Can you take this from here?

**Comment by idohalevi** [comment]
@rudaporto @roiravhon 
I will need some time to get into this. @rudaporto how urgent it is for you?

**Comment by rudaporto** [comment]
I'm using my fork, but I guess you have no time to add PyPy support to this library.
Let me know if you need anything from my side.

**Comment by idohalevi** [comment]
@rudaporto 
Thank you
