### ISSUE TITLE
Allow to disable logs to disk

### ISSUE THREAD

**Issue by Sytten** [logzio/logzio-python-handler#35]
Currently there is no way to override the `should_backup_to_disk` so that it doesn't log even if the sending failed. In our application this is problematic.

**Comment by idohalevi** [comment]
Hi @Sytten 
I will add this feature to our to-do feature list. 
At the moment, I can't promise any timeline so feel free to send a PR if it's urgent

**Comment by Sytten** [comment]
Thanks! For the moment we patched the `backup_logs` function to do nothing so it works, but it's not very clean. I might do a PR if I have the time.

**Comment by Sytten** [comment]
There you go: https://github.com/logzio/logzio-python-handler/pull/36
