### ISSUE TITLE
LogzioHandler.format_message overwrites exc_info although needed by other handlers

### ISSUE THREAD

**Issue by yakirsudry** [logzio/logzio-python-handler#42]
I'm using the LogzioHandler and also some other handlers (e.g console, or FileHandler).
The problem arises when I pass exc_info to logging of the message.

LogzioHandler.format_message deletes this value from the record, although it is used by other handlers that will receive this record.

**Comment by idohalevi** [comment]
@yakirsudry 
Can you share how you configure your logger? I believe I encountered this before and changing the order of the handlers where Logzio is last solved it

**Comment by yakirsudry** [comment]
I have 3 handlers.
1. console
2. Logzio
3. File

From reading the code I think you are right. It comes from the following code:

`
        if message.exc_info:
            return_json['exception'] = self.format_exception(message.exc_info)

            # We want to ignore default logging formatting on exceptions
            # As we handle those differently directly into exception field
            message.exc_info = None
            message.exc_text = None
`

I believe your solution might solve that (I'll try that soon). But still, I believe it's strange behavior.

**Comment by tamir-michaeli** [comment]
Fixed in #66
