### ISSUE TITLE
Logs not shipped when use this handler in AWS Lambda

### ISSUE THREAD

**Issue by cmpxchg16** [logzio/logzio-python-handler#43]
Hi.

From looking into the code I see there is a non-daemon Thread that responsible to drain
the queue based on configureable timeout, but in Lambda, when the handler done, 
from Lambda perspective, the code is done, so the drain Thread not happened.
I tried to do explicit flush by calling: `logging.shutdown()` after adding only one small string to log,
but then what happened, is that logs are shipped successfully, but it take 30 seconds to done this call by spending too much time inside the loop without doing nothing :(

One more note, when run the same code from local machine - everything is ok (both Python 3.6 & 3.7).

logging yaml config:

```
  version: 1
  disable_existing_loggers: True
  formatters:
    logzioFormat:
      format: '{"service": "Lambda", "environment": "dev"}'

  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      stream: ext://sys.stdout
    logzio:
      class: logzio.handler.LogzioHandler
      level: DEBUG
      formatter: logzioFormat
      token: 
      logzio_type: next_insurance_python
      logs_drain_timeout: 1
      url: https://listener.logz.io:8071
      debug: True

  root:
    handlers: [logzio, console]
    level: DEBUG

```

code using it:

```
logging.config.dictConfig(yamlConfig)
logger = logging.getLogger('superAwesomeLogzioLogger')
logger.info('lambda handler starts')
```

Please advice..
Thanks.

**Comment by idohalevi** [comment]
@cmpxchg16 
Why not use the default logger -> cloudwatch -> logz.io?

**Comment by cmpxchg16** [comment]
> @cmpxchg16
> Why not use the default logger -> cloudwatch -> logz.io?

I saw that solution, but from different reasons it's not fit our needs.

**Comment by roiravhon** [comment]
Hi @cmpxchg16, check this out:
https://github.com/logzio/logzio-python-handler/pull/18

Just call flush() in the end, should  work

**Comment by mcmasty** [comment]
@cmpxchg16 , @roiravhon 

FWIW, I created a decorator that calls `flush()` on all handlers configured.

The [Gist is here](https://gist.github.com/mcmasty/55daf0a1fa15b9c7034a72448ff2d6ce) 

Perhaps logzIO team can adapt the decorator and make it part of the core Python package ?

**Comment by roiravhon** [comment]
@idohalevi WDYS?

**Comment by idohalevi** [comment]
@roiravhon  It looks good to me. 
If you want I can add it to my team tasks

**Comment by roiravhon** [comment]
@idohalevi yep, think so. Let's wrap it nicely in the appender, it makes sense to support that (or similar more generic) functionality.

**Comment by idohalevi** [comment]
#50
