### ISSUE TITLE
Endless loop when network is down

### ISSUE THREAD

**Issue by raviv** [logzio/logzio-python-handler#45]
Hi,

Is there a way to configure the handler so that it doesn't retry sending logs endlessly when network is down?
Currently it's trying in an endless loop and I can't even stop my app with CTRL+C.
I'm deploying the app in an env when network is not always available and I want it to send logs only when net is up.
I also don't want it to accumulate logs when net is down.

Thanks,
Raviv

**Comment by idohalevi** [comment]
@raviv I'm not sure why would you want that. It means you will lose data. Can you explain the use case? Also, how can you distinguish between when the network is down because you set it like that and not?

**Comment by raviv** [comment]
@idohalevi The device is deployed in an environment where network is not always available.
I realise I loose data but it's ok, the events are relevant only when net is up.

**Comment by idohalevi** [comment]
@raviv If you set up backup logs flag to false it should answer your use case. We will try to send but after 3 times give up
