### ISSUE TITLE
The LogzioHandler is not process safe

### ISSUE THREAD

**Issue by stelles** [logzio/logzio-python-handler#48]
I am finding issues with the handler that when multiple processes use the same logger that has this handler, or even if they spawn their own handler, when joining the process, it hangs forever.

I have circumvented this by using a single LogzioSender instance, which is thread/process safe because of the queues, then spawning handlers that contain this sender (rather than create their own).

Potentially I am doing this wrong or this is bad practice but I haven't seen any other way.

I am using Python2.7.13 and logzio-python-handler==2.0.13.

**Comment by idohalevi** [comment]
@stelles Thank you for letting us know. 
I will try to fix it ASAP but it might take some time

**Comment by Jakobovski** [comment]
@idohalevi  I believe we are having the same issue

**Comment by Jakobovski** [comment]
@stelles Can you please share your fix? Thanks!

**Comment by c0rvax** [comment]
Hey @idohalevi 

Can I get a discount for logz.io service if I submit a PR to this issue? :D

**Comment by jkowall** [comment]
Maybe, what did you have in mind? :)

**Comment by c0rvax** [comment]
@jkowall 

I was thinking about adapting one of the common solutions to make it work with logz.io. For example this repo https://github.com/jruere/multiprocessing-logging 

Basically the idea is to spawn a thread with `multiprocessing.Queue` which is used to consume the data and send it to the server (or file, as in that repo). All logger clients (users) simply push their records into the mentioned `Queue`

**Comment by stelles** [comment]
@Jakobovski I'm sorry I never replied last year.

I ended up doing something like @c0rvax. From the master process, spawn a master thread which will be the flushing thread and it will contain the multiprocessing queue.  Then for other processes, they need to use a static method which returns the main threads multiprocessing queue and it will push the logs to that queue.

I unfortunately no longer work at the company so I don't have access to the code but I can see if I can create a PR.

**Comment by tamir-michaeli** [comment]
Hi guys, we are trying to solve the issue but cannot reproduce it, does anyone have a reproduction for this?

**Comment by Jakobovski** [comment]
I vaguely remember this being a python2 issue. Maybe try to reproduce in Py2 to confirm

**Comment by tamir-michaeli** [comment]
Thanks @Jakobovski !
After testing with Python2.7.13 and the python handler 2.0.13 i did not managed to recreate the issue above (the processes are successfully ending), but i did manage to have consistency issues - some of the processes had trouble sending the logs.
Tested again with python 3.9, and the issue does not exist.

**Comment by tamir-michaeli** [comment]
Inactive - closed.

**Comment by AlexanderOtavka** [comment]
For anyone else encountering this issue and finding themselves here: be sure you have set the log level on your logz.io handler to `INFO`.  Otherwise, it will hang on shutdown because the handler itself creates debug messages on shutdown that it will keep trying to flush in an infinite loop.
