### ISSUE TITLE
Question: Can this be used to send custom metrics?

### ISSUE THREAD

**Issue by Galbar** [logzio/logzio-python-handler#58]
Hi, I'm checking the new metrics tab in app.logz.io.

Is there any way to send custom metrics to it from Python?

I have been sending metrics to Kibana using a LogzioHandler and passing the metrics in the `extra` parameter. It would be awesome if I could display them in Grafana, either those or new ones sent to the metrics API.

**Comment by idohalevi** [comment]
@Galbar Hi! do you have an infrastructure monitoring account or just a log analytics account?

**Comment by Galbar** [comment]
Hi @idohalevi,

I have a free account that gives me:
Kibana logs:
3 GB total daily volume
3 days retention
Metrics account plan:
1000 unique metrics

I have been toying with the platform and was wondering if there was a way to publish custom metrics from my test service

**Comment by idohalevi** [comment]
@Galbar you can use the following: https://docs.logz.io/user-guide/infrastructure-monitoring/custom-metrics

Make sure to use the Metric account shipping token. Let us know if you need help

**Comment by Galbar** [comment]
Thanks! I couldn't find that yesterday. Awesome!

**Comment by Galbar** [comment]
So, I've formatted my metrics to follow the json format specified in the docs. Here is an example:
```json
{
  "metrics": {
    "test.web.request.time": 0.5160647630691528,
    "test.web.request.count": 2.0
  },
  "dimensions": {
    "method": "GET",
    "path": "/test_path/{resource:.*}",
    "status": 200
  }
}
```

I'm passing the json string to a logger configured with the LogzioHandler.

```python
logger.addHandler(LogzioHandler(config.get('logzio.metrics.token'), debug=True))
...
logger.info(metric_json)
```

I'm not seeing the metrics on the platform. I made sure I'm using the right token and I even set the LogzioHandler to debug and it says it sends the log successfully.

I'm checking by running the query `NOT event.module: docker`, to filter out everything else I'm already sending (the docker metrics collector), in the explore tab in grafana.

Is that the correct way to send them? If not which is it? I couldn't find it in the docs

**Comment by Galbar** [comment]
@idohalevi ping?

**Comment by idohalevi** [comment]
@Galbar the logger will parse the json to a log format so I think it will ruin the way your json looks like. @mirii1994 @Doron-Bargo maybe we need to add a way to ship custom metrics from our log appenders across all programing languages?

**Comment by Doron-Bargo** [comment]
@Galbar for our old backend ( based on elastic ) you can use this logger
For sending metrics to the new Prometheus as a service you should use this link
https://docs.logz.io/shipping/prometheus-sources/python-custom-prometheus.html
