### ISSUE TITLE
[Docs] additional_field

### ISSUE THREAD

**Issue by nirgn975** [logzio/logzio-python-handler#6]
I'm trying to use this library and logging to logz.io. But I couldn't understand how to change the value from being hardcoded string to a variable I can pass from my code when I do logging:

The `additional_field` in logz.io dashboard:
<img width="867" alt="logz_io" src="https://cloud.githubusercontent.com/assets/3472902/26772006/89d55f7a-49cb-11e7-8eae-a4b8a16872d2.png">

I appreciate any help because it's not clear from the `README.md`

**Comment by roiravhon** [comment]
The format={"additional_field": "value"} section was just an example of how to use this :)
In case you need some additional fields to be added to each log message, this is how to use it.
If you don't, you can just omit this 

format={}

**Comment by nirgn975** [comment]
I'm sorry but I wasn't clear. I do need some additional fields, but in your example it's insert a hard coded string (e.g. `"value"`). And I need it to be a variable so I can log additional info, like:
```
logger.info('This is a the message', additional_field='foo')
```

And in other place do something like:
```
logger.info('This is a the message2', additional_field='bar')
```

**Comment by roiravhon** [comment]
Got you.
Well, this is not supported currently.

Do you know a handler that has this functionality that I can look at?

**Comment by nirgn975** [comment]
1. [https://github.com/vklochan/python-logstash](https://github.com/vklochan/python-logstash)
2. [https://github.com/ulule/python-logstash-formatter](https://github.com/ulule/python-logstash-formatter)

In both of them you can pass `extra` fields.

**Comment by roiravhon** [comment]
Cool. Adding a feature request

**Comment by naphtul** [comment]
This feature will be very useful for us.

**Comment by roiravhon** [comment]
Hey guys, this was just merged
https://github.com/logzio/logzio-python-handler/pull/15

Update to version 2.0.5 to get the functionality. Sorry it took so long :)
