### ISSUE TITLE
Can't make it work on production (AWS Elasticbeanstalk)

### ISSUE THREAD

**Issue by lowercase00** [logzio/logzio-python-handler#61]
Hi there.
I have a Flask Application running on Beanstalk. 
I followed the recommended configuration, and it does seem to work  just fine while running locally, but when I deploy my service I can't get the logs on the platform. The configuration I've tried:

```
app/__init__.py
import logging

logger = logging.getLogger(__name__)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'logzioFormat': {
            'format': '{"additional_field": "value"}',
            'validate': False
        }
    },
    'handlers': {
        'logzio': {
            'class': 'logzio.handler.LogzioHandler',
            'level': 'DEBUG',
            'formatter': 'logzioFormat',
            'token': 'MYTOKEN',
            'logs_drain_timeout': 5,
            'url': 'https://listener.logz.io:8071'
        }
    },
    'loggers': {
        '': {
            'level': 'DEBUG',
            'handlers': ['logzio'],
            'propogate': True
        }
    }
}
def create_logger():

    logging.config.dictConfig(LOGGING)
    logger = logging.getLogger('superAwesomeLogzioLogger')

def app_factory():
    create_logger()
```

On my modules, spread accross a few files I always have:
```
app/modules/routes.py

import logging

logger = logging.getLogger(__name__)
logger.info('log message')
```

What am I missing?

**Comment by lowercase00** [comment]
I just so an issue related to uWSGI, so I'm guessing there must be something similar to that.
I'm also using threads in the application, but I currently don't have access to uWSGI configuration.

The only logger I can see is the logger.info('Starting in Production environment') in my app_factory (right after the create_logger() function), the funny thing is, I call my app_factory() in an application.py file, which starts a thread (read SQS) before the if __name__ == '__main__'. So this single log works even though the second thread had already started.

**Comment by tamir-michaeli** [comment]
Hi #lowercase00 , im trying to understand the code snippet you shared. Seems like you are initializing the __name__ logger with no configuration, and then calling it from your modules. Looks like the the 'superAwesomeLogzioLogger' is the one with the logzio handler configuration, so you should try and use it from your modules (or initialize the __name__ logger).

**Comment by tamir-michaeli** [comment]
Issue is stale, closed.
