### ISSUE TITLE
Remove the creation of debug files

### ISSUE THREAD

**Issue by WebDesignSun** [logzio/logzio-python-handler#62]
I am using django here are my settings
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
        'logzioFormat': {
            'format': '{"additional_field": "value"}',
            'validate': False
        }
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'level': 'DEBUG',
            'formatter': 'verbose'
        },
        'logzio': {
            'class': 'logzio.handler.LogzioHandler',
            'level': 'INFO',
            'formatter': 'logzioFormat',
            'token': '<<TOKEN>>',
            'logzio_type': "python",
            'logs_drain_timeout': 5,
            'url': 'https://listener.logz.io:8071',
            'debug': False,
            'backup_logs': False,
            'network_timeout': 10,
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', ],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO')
        },
        'fulfill': {
            'handlers': ['logzio'],
            'level': 'INFO'
        }
    }
}

And I have a debug file created all the time logzio-failures-15022021-084105.txt
What settings should I apply so that the file is not created?

**Comment by WebDesignSun** [comment]
This is how I am sending data to logz.io

import logging.config
import logging
from .settings import LOGGING, EXTRA

logging.config.dictConfig(LOGGING)
logger = logging.getLogger('fulfill')
logger.info('test info', extra=EXTRA)

**Comment by mirii1994** [comment]
Hi @WebDesignSun ,
First, please try to refrain from publishing you shipping token when posting :)
Second, any chance that this file was created before you set the `backup_logs` flag as False? I tried running it with your configuration and it didn't create a file for me on failure.

**Comment by mirii1994** [comment]
Hi @WebDesignSun ,
Any chance that this file was created before you set the backup_logs flag as False? I tried running it with your configuration and it didn't create a file for me on failure.

**Comment by WebDesignSun** [comment]
files are created even after setting the flag to false. my version logzio-python-handler==3.0.0

**Comment by tamir-michaeli** [comment]
Tested and could not reproduce - debug files only created when debug flag is True.

**Comment by tamir-michaeli** [comment]
Inactive - closed.
