### ISSUE TITLE
breaking change on released version 3.0.0

### ISSUE THREAD

**Issue by DanielRap** [logzio/logzio-python-handler#69]
this pr https://github.com/logzio/logzio-python-handler/pull/66/files seemed to be merged and was released again to 3.0.0, I guess the intention was to release it on 3.1.0 only.
the following command worked fine yesterday and resulting a conflict today.
pip install logzio-python-handler==3.0.0 requests==2.24.0

**Comment by tzurgross** [comment]
yes! this PR broke our services today

**Comment by tamir-michaeli** [comment]
@DanielRap I reuploaded version 3.0.0, please try again

**Comment by tamir-michaeli** [comment]
@DanielRap had a chance to verify if the issue is resolved?

**Comment by DanielRap** [comment]
> @DanielRap had a chance to verify if the issue is resolved?

Yes sorry for my delayed response and thanks for the quick turnaround
