### ISSUE TITLE
Returning formatted message instead of the format string.

### ISSUE THREAD

**Issue by johnraz** [logzio/logzio-python-handler#7]
Hi there,

I just wanted to ask if you did use `message.msg` on purpose [here](https://github.com/logzio/logzio-python-handler/blob/master/logzio/handler.py#L42) to avoid potential information leak or not?

Just to give a bit more context on this and be sure I'm completely clear:
```
logger.info('Hello %s', 'world')
```
will result into the following `LogRecord` behavior:
```
> print log_record.msg 
"Hello %s"
> print log_record.message
"Hello world"
```

Is there anything I'm missing that allows to go around this?

If you want this to be changed, I'll make a PR.

Cheers.

**Comment by roiravhon** [comment]
Hey @johnraz!
Well, that seems like a bug :)

a PR would be great! thanks

**Comment by johnraz** [comment]
@roiravhon see #8 ;-)
