### ISSUE TITLE
Exception logging not respecting logzio_type

### ISSUE THREAD

**Issue by tylfin** [logzio/logzio-python-handler#9]
Unlike `logging.info(...)`, `logging.exception(...)` does not carry the logzio_type making it impossible to find these messages. Instead it overwrites type to:```type: logzio-invalid-log```.

**Comment by roiravhon** [comment]
It should carry the type just as regular log message.
logzio-invalid-log represents a log that was usually too big for elasticsearch to index (or other reason elasticsearch prevented the log)

The stacktrace might be too big?
Please see if in logz.io the log message have three dots at the end of the message field (...)

**Comment by tylfin** [comment]
@roiravhon Yup, it looks like the stacktrace is too big to be indexed. Is there any way to have the logger / logz to split the error into multiple logs (or worse case scenario, truncate)?

**Comment by roiravhon** [comment]
Our system truncates the logs now to a size which can be indexed in ES.
Splitting the error meaning duplicating some logic from our backend, we need to think this through internally.

@asafm thoughts?

**Comment by tylfin** [comment]
@roiravhon The system truncation is fine for now, but when it overwrites the type to 'logzio-invalid-log' it makes querying for the stacktraces really difficult. Is there a less involved solution of remapping the invalid-log flag to a different field? (for example, we use the type to indicate the environment + service)

**Comment by roiravhon** [comment]
@tylfin agreed.
I'll open an internal ticket for that

**Comment by mr337** [comment]
Any update on this?

**Comment by roiravhon** [comment]
Hey @mr337, unfortunately, no.
Please reach out to support via the in-app chat and they will work with you on that issue.

**Comment by tamir-michaeli** [comment]
Issue is stale, tested the log type is carried with all types of log.
