### ISSUE TITLE
Remove pin on `opentelemetry-instrumentation-logging`

### ISSUE THREAD

**Issue by setu4993** [logzio/logzio-python-handler#97]
The package `opentelemetry-instrumentation-logging` is [pinned to v0.39.0](https://github.com/logzio/logzio-python-handler/blob/master/setup.py#L21C36-L21C73) which forces the use of `opentelemetry-instrumentation` packages with v0.39b. The instrumentation packages have a CVE that affects 0.39 (resolved in v0.41b): https://github.com/advisories/GHSA-5rv5-6h4r-h22v

Can the pin please be removed and the package updated to a more recent version?

**Comment by ralongit** [comment]
Hello @setu4993 ,
Thank you, we have upgraded the version(#92 ) from v0.390b to v0.45b0 in release v4.1.4 of the python handler. 
We will leave the pin and keep the versions updated.

**Comment by setu4993** [comment]
Got it. Thanks. Curious about the reasoning behind keeping the versions pinned when OpenTelemetry follows [semantic versioning](https://opentelemetry.io/docs/specs/otel/versioning-and-stability/).

It does seem that'd be stable.

**Comment by yotamloe** [comment]
Hi @setu4993

Thanks for bringing this up! We keep the version pinned mainly for stability and to avoid any surprises with automatic updates. It helps us ensure everything works smoothly and avoids any unexpected issues.

Pinning also helps us manage security risks better. We can thoroughly test updates before releasing them, ensuring no new security vulnerabilities are introduced.

Even though OpenTelemetry uses semantic versioning, pinning lets us control any potential conflicts and maintain a consistent experience.

Hope this helps! Let us know if you have more questions.

**Comment by setu4993** [comment]
Thanks for that context and engaging on this.

From the [source I can see](https://github.com/logzio/logzio-python-handler/blob/master/logzio/handler.py#L44-L51) I don't think it's particularly risky, but I admit I don't have the complete picture.

I hope the Logz.io team will consider removing the pin in the future.

Regardless, given this is now updated to atleast the current latest version, I'm going to close this issue.

Thanks, again, for jumping on this quickly and explaining your reasoning.
